version: "3.7"

services:
  ubuntu1:
    build: .
    container_name: ubuntu1
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # volumes:
    #   - .:/home/tumypmyp
    networks:
      app_net:
        ipv4_address: 192.168.0.11
            
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"